version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          if [ $CIRCLE_TAG ]
          then
            # We have a tag, build and push the docker image
            docker build -t wunderio/circleci-builder:$CIRCLE_TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push wunderio/circleci-builder:$CIRCLE_TAG
          else
            # No tag is present, we only test that the build works.
            docker build .
          fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
