version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2.0.0

workflows:
  btd:
    jobs:
      - orb-tools/publish:  &publish
          pre-steps:
            - checkout
            - run:
                name: Pack the orb
                command: circleci config pack orb/ > orb.yml

          name: "Publish development orb"
          orb-path: orb.yml
          orb-ref: silta/silta@dev:${CIRCLE_BRANCH}
          publish-token-variable: "$CIRCLECI_DEV_API_TOKEN"
          validate: true

      - orb-tools/publish:
          <<: *publish
          name: "Publish production orb"
          orb-ref: silta/silta@${CIRCLE_TAG}
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
            branches:
              ignore: /.*/
