version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - setup_remote_docker

      # build and push Docker image
      - run: |
          docker build -t   wunderio/circleci-builder:k8s . 
          docker login -u $DOCKER_USER -p $DOCKER_PASS   
          docker push wunderio/circleci-builder:k8s

