version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # build and push Docker image
      - run: |
          TAG=1.$CIRCLE_BUILD_NUM
          docker build -t   wunderio/circleci-builder:$TAG . 
          docker tag wunderio/circleci-builder:$TAG wunderio/circleci-builder:latest
          docker login -u $DOCKER_USER -p $DOCKER_PASS   
          docker push wunderio/circleci-builder:$TAG
          docker push wunderio/circleci-builder:latest

workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only: master
